"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-23 10:03:39.287581
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('alert_code', sa.String(length=64), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('disease', sa.String(length=128), nullable=True),
    sa.Column('is_broadcast', sa.Boolean(), nullable=True),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=True),
    sa.Column('dedup_key', sa.String(length=191), nullable=True),
    sa.Column('related_entity_type', sa.String(length=32), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_level', sa.String(length=32), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_code'), ['alert_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('data_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('quality_report', sa.JSON(), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'dataset', 'content_hash', name='uq_snapshot_hash')
    )
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_snapshots_provider'), ['provider'], unique=False)

    op.create_table('data_source_status',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('external_data_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('data_status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('data_version', sa.String(length=32), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_data_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_data_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_data_records_provider'), ['provider'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_scope', 'key', name='uq_idem_scope_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_created_at'), ['created_at'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=191), nullable=True),
    sa.Column('run_after', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('laboratories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('accreditation', sa.String(length=128), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laboratories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_laboratories_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_laboratories_id'), ['id'], unique=False)

    op.create_table('outbreak_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('outbreak_code', sa.String(length=64), nullable=True),
    sa.Column('disease', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('affected_count', sa.Integer(), nullable=True),
    sa.Column('death_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('evidence_level', sa.String(length=32), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('detection_method', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('date_detected', sa.DateTime(), nullable=True),
    sa.Column('date_contained', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbreak_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbreak_events_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbreak_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbreak_events_outbreak_code'), ['outbreak_code'], unique=True)

    op.create_table('surveillance_observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('disease', sa.String(length=128), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('block', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('death_count', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('data_version', sa.String(length=32), nullable=True),
    sa.Column('raw_reference', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_record_id', name='uq_obs_source_record')
    )
    with op.batch_alter_table('surveillance_observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_district_disease_observed', ['district', 'disease', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveillance_observations_disease'), ['disease'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveillance_observations_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveillance_observations_observed_at'), ['observed_at'], unique=False)

    op.create_table('sync_conflicts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('server_version', sa.Integer(), nullable=True),
    sa.Column('client_data', sa.JSON(), nullable=False),
    sa.Column('server_data', sa.JSON(), nullable=False),
    sa.Column('conflicting_fields', sa.JSON(), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_conflicts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_user_id'), ['user_id'], unique=False)

    op.create_table('sync_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('client_sync_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_events_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('division', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('license_number', sa.String(length=128), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('service_area', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('notification_language', sa.String(length=8), nullable=True),
    sa.Column('sms_opt_in', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_taluka'), ['taluka'], unique=False)

    op.create_table('vaccination_campaigns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('campaign_code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('disease', sa.String(length=128), nullable=False),
    sa.Column('vaccine', sa.String(length=128), nullable=False),
    sa.Column('species', sa.JSON(), nullable=True),
    sa.Column('target_districts', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('target_population', sa.Integer(), nullable=True),
    sa.Column('coverage_target_percent', sa.Float(), nullable=True),
    sa.Column('current_vaccinated', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccination_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccination_campaigns_campaign_code'), ['campaign_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_vaccination_campaigns_id'), ['id'], unique=False)

    op.create_table('veterinary_facilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('mvu_available', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veterinary_facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veterinary_facilities_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_facilities_taluka'), ['taluka'], unique=False)

    op.create_table('workflow_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=True),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('disease_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_number', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_role', sa.String(length=32), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('number_affected', sa.Integer(), nullable=False),
    sa.Column('number_dead', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('temperature_unit_reported', sa.String(length=1), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_status', sa.String(length=32), nullable=False),
    sa.Column('suspected_disease', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('triage_urgency', sa.String(length=32), nullable=True),
    sa.Column('triage_risk_level', sa.String(length=32), nullable=True),
    sa.Column('triage_recommendations', sa.JSON(), nullable=True),
    sa.Column('triage_confidence', sa.Float(), nullable=True),
    sa.Column('triage_rule_version', sa.String(length=32), nullable=True),
    sa.Column('triage_explanation', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verified_by_id', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('number_affected >= 0', name='ck_reports_affected_nonneg'),
    sa.CheckConstraint('number_dead >= 0', name='ck_reports_dead_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disease_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disease_reports_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_report_number'), ['report_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_disease_reports_reported_at'), ['reported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_species'), ['species'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_suspected_disease'), ['suspected_disease'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_taluka'), ['taluka'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_triage_risk_level'), ['triage_risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index('ix_reports_district_status_created', ['district', 'status', 'created_at'], unique=False)

    op.create_table('farms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('total_area_acres', sa.Float(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_farms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farms_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farms_taluka'), ['taluka'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=191), nullable=True),
    sa.Column('delivery_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('stored_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('related_entity_type', sa.String(length=32), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_files_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_related_entity_id'), ['related_entity_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('vaccination_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('animal_id', sa.String(length=64), nullable=False),
    sa.Column('herd_id', sa.String(length=64), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('disease', sa.String(length=128), nullable=False),
    sa.Column('vaccine', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('batch_number', sa.String(length=64), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('vaccination_date', sa.DateTime(), nullable=True),
    sa.Column('vaccination_day', sa.String(length=10), nullable=False),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('provider_name', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('adverse_event', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['vaccination_campaigns.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'disease', 'dose_number', 'vaccination_day', name='uq_vacc_animal_disease_dose_day')
    )
    with op.batch_alter_table('vaccination_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccination_records_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccination_records_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccination_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccination_records_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccination_records_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccination_records_vaccination_date'), ['vaccination_date'], unique=False)

    op.create_table('veterinarian_profiles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('location_accuracy_m', sa.Float(), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('service_radius_km', sa.Float(), nullable=False),
    sa.Column('has_transport', sa.Boolean(), nullable=False),
    sa.Column('max_active_cases', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('veterinarian_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veterinarian_profiles_availability_status'), ['availability_status'], unique=False)

    op.create_table('herds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('total_animals', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('herds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_herds_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_herds_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_herds_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_herds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_herds_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_herds_taluka'), ['taluka'], unique=False)
        batch_op.create_index(batch_op.f('ix_herds_updated_at'), ['updated_at'], unique=False)

    op.create_table('animals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.String(length=64), nullable=True),
    sa.Column('herd_id', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('breed', sa.String(length=128), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('age_years', sa.Float(), nullable=True),
    sa.Column('health_status', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'tag_id', name='uq_animals_owner_tag')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_herd_id'), ['herd_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_taluka'), ['taluka'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_updated_at'), ['updated_at'], unique=False)

    op.create_table('veterinary_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=True),
    sa.Column('report_id', sa.String(length=64), nullable=True),
    sa.Column('animal_id', sa.String(length=64), nullable=True),
    sa.Column('herd_id', sa.String(length=64), nullable=True),
    sa.Column('farmer_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_vet_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('taluka', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('reported_problem', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_prescribed', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('requires_lab', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('en_route_at', sa.DateTime(), nullable=True),
    sa.Column('on_site_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['assigned_vet_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['disease_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veterinary_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veterinary_cases_assigned_vet_id'), ['assigned_vet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_taluka'), ['taluka'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_cases_updated_at'), ['updated_at'], unique=False)

    op.create_table('dispatch_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('vet_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('distance_basis', sa.String(length=32), nullable=True),
    sa.Column('eta_minutes', sa.Float(), nullable=True),
    sa.Column('eta_status', sa.String(length=32), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['veterinary_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_requests', schema=None) as batch_op:
        batch_op.create_index('ix_dispatch_case_status', ['case_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_requests_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_requests_vet_id'), ['vet_id'], unique=False)

    op.create_table('lab_samples',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sample_code', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('animal_id', sa.String(length=64), nullable=True),
    sa.Column('farmer_id', sa.String(length=64), nullable=True),
    sa.Column('lab_id', sa.String(length=64), nullable=True),
    sa.Column('collected_by_id', sa.String(length=64), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('disease_suspected', sa.String(length=128), nullable=False),
    sa.Column('sample_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('collection_lat', sa.Float(), nullable=True),
    sa.Column('collection_lng', sa.Float(), nullable=True),
    sa.Column('qr_code', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.String(length=64), nullable=True),
    sa.Column('verified_by_name', sa.String(length=128), nullable=True),
    sa.Column('verification_remarks', sa.Text(), nullable=True),
    sa.Column('final_result', sa.String(length=32), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('external_lims_id', sa.String(length=128), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['veterinary_cases.id'], ),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_samples_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_samples_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_samples_disease_suspected'), ['disease_suspected'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_samples_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_samples_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_samples_lab_id'), ['lab_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_samples_sample_code'), ['sample_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lab_samples_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_samples_updated_at'), ['updated_at'], unique=False)

    op.create_table('veterinary_visits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('vet_id', sa.String(length=64), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('treatment_given', sa.Text(), nullable=True),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['veterinary_cases.id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veterinary_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veterinary_visits_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_veterinary_visits_id'), ['id'], unique=False)

    op.create_table('custody_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_from', sa.String(length=128), nullable=True),
    sa.Column('transfer_to', sa.String(length=128), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('transport_status', sa.String(length=64), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_label', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['lab_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custody_events_sample_id'), ['sample_id'], unique=False)

    op.create_table('lab_tests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=True),
    sa.Column('test_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('tested_by_id', sa.String(length=64), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.Column('result_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['lab_samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_tests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_sample_id'), ['sample_id'], unique=False)

    op.create_table('lab_result_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('entered_by_id', sa.String(length=64), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_result_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_result_revisions_test_id'), ['test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_result_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_result_revisions_test_id'))

    op.drop_table('lab_result_revisions')
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_tests_sample_id'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_id'))

    op.drop_table('lab_tests')
    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custody_events_sample_id'))

    op.drop_table('custody_events')
    with op.batch_alter_table('veterinary_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veterinary_visits_id'))
        batch_op.drop_index(batch_op.f('ix_veterinary_visits_case_id'))

    op.drop_table('veterinary_visits')
    with op.batch_alter_table('lab_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_samples_updated_at'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_status'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_sample_code'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_lab_id'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_id'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_district'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_disease_suspected'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_created_at'))
        batch_op.drop_index(batch_op.f('ix_lab_samples_case_id'))

    op.drop_table('lab_samples')
    with op.batch_alter_table('dispatch_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_requests_vet_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_requests_status'))
        batch_op.drop_index(batch_op.f('ix_dispatch_requests_case_id'))
        batch_op.drop_index('ix_dispatch_case_status')

    op.drop_table('dispatch_requests')
    with op.batch_alter_table('veterinary_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_updated_at'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_taluka'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_status'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_report_id'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_id'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_district'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_case_number'))
        batch_op.drop_index(batch_op.f('ix_veterinary_cases_assigned_vet_id'))

    op.drop_table('veterinary_cases')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_updated_at'))
        batch_op.drop_index(batch_op.f('ix_animals_taluka'))
        batch_op.drop_index(batch_op.f('ix_animals_tag_id'))
        batch_op.drop_index(batch_op.f('ix_animals_owner_id'))
        batch_op.drop_index(batch_op.f('ix_animals_id'))
        batch_op.drop_index(batch_op.f('ix_animals_herd_id'))
        batch_op.drop_index(batch_op.f('ix_animals_farm_id'))
        batch_op.drop_index(batch_op.f('ix_animals_district'))
        batch_op.drop_index(batch_op.f('ix_animals_created_at'))

    op.drop_table('animals')
    with op.batch_alter_table('herds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_herds_updated_at'))
        batch_op.drop_index(batch_op.f('ix_herds_taluka'))
        batch_op.drop_index(batch_op.f('ix_herds_owner_id'))
        batch_op.drop_index(batch_op.f('ix_herds_id'))
        batch_op.drop_index(batch_op.f('ix_herds_farm_id'))
        batch_op.drop_index(batch_op.f('ix_herds_district'))
        batch_op.drop_index(batch_op.f('ix_herds_created_at'))

    op.drop_table('herds')
    with op.batch_alter_table('veterinarian_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veterinarian_profiles_availability_status'))

    op.drop_table('veterinarian_profiles')
    with op.batch_alter_table('vaccination_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccination_records_vaccination_date'))
        batch_op.drop_index(batch_op.f('ix_vaccination_records_updated_at'))
        batch_op.drop_index(batch_op.f('ix_vaccination_records_next_due_date'))
        batch_op.drop_index(batch_op.f('ix_vaccination_records_id'))
        batch_op.drop_index(batch_op.f('ix_vaccination_records_district'))
        batch_op.drop_index(batch_op.f('ix_vaccination_records_animal_id'))

    op.drop_table('vaccination_records')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_family_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_related_entity_id'))
        batch_op.drop_index(batch_op.f('ix_stored_files_owner_id'))
        batch_op.drop_index(batch_op.f('ix_stored_files_expires_at'))

    op.drop_table('stored_files')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_taluka'))
        batch_op.drop_index(batch_op.f('ix_farms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_farms_id'))
        batch_op.drop_index(batch_op.f('ix_farms_district'))

    op.drop_table('farms')
    with op.batch_alter_table('disease_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_district_status_created')
        batch_op.drop_index(batch_op.f('ix_disease_reports_verification_status'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_updated_at'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_triage_risk_level'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_taluka'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_suspected_disease'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_status'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_species'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_reported_at'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_report_number'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_is_demo'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_id'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_district'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_client_id'))

    op.drop_table('disease_reports')
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_created_at'))

    op.drop_table('workflow_events')
    with op.batch_alter_table('veterinary_facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veterinary_facilities_taluka'))
        batch_op.drop_index(batch_op.f('ix_veterinary_facilities_district'))

    op.drop_table('veterinary_facilities')
    with op.batch_alter_table('vaccination_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccination_campaigns_id'))
        batch_op.drop_index(batch_op.f('ix_vaccination_campaigns_campaign_code'))

    op.drop_table('vaccination_campaigns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_taluka'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_district'))

    op.drop_table('users')
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_sync_events_id'))

    op.drop_table('sync_events')
    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_status'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_entity_id'))

    op.drop_table('sync_conflicts')
    with op.batch_alter_table('surveillance_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveillance_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_surveillance_observations_district'))
        batch_op.drop_index(batch_op.f('ix_surveillance_observations_disease'))
        batch_op.drop_index('ix_obs_district_disease_observed')

    op.drop_table('surveillance_observations')
    with op.batch_alter_table('outbreak_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbreak_events_outbreak_code'))
        batch_op.drop_index(batch_op.f('ix_outbreak_events_id'))
        batch_op.drop_index(batch_op.f('ix_outbreak_events_district'))

    op.drop_table('outbreak_events')
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laboratories_id'))
        batch_op.drop_index(batch_op.f('ix_laboratories_district'))
        batch_op.drop_index(batch_op.f('ix_laboratories_code'))

    op.drop_table('laboratories')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedup_key'))

    op.drop_table('jobs')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_created_at'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('external_data_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_data_records_provider'))
        batch_op.drop_index(batch_op.f('ix_external_data_records_id'))

    op.drop_table('external_data_records')
    op.drop_table('data_source_status')
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_snapshots_provider'))

    op.drop_table('data_snapshots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_district'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_code'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
